CREATE TABLE sensorStatus (
  ID SERIAL PRIMARY KEY,
  status INTEGER NOT NULL,
  tijd TIMESTAMP WITH TIME ZONE NOT NULL,
  opmerking VARCHAR(128)
);

CREATE TABLE buttonPresses (
  ID SERIAL PRIMARY KEY,
  tijd TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE SpeedTrap (
  ID SERIAL PRIMARY KEY,
  tijd TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE totaalKnikkers (
  ID SERIAL PRIMARY KEY,
  totaal INTEGER,
  tijd TIMESTAMP WITH TIME ZONE NOT NULL,
  opmerking VARCHAR(128)
);

